### ISSUE TITLE
Error with new googlesearch package

### ISSUE THREAD

**Issue by sa1g0n1337** [six2dez/dorks_hunter#4]
The new **googlesearch** package returned an error saying `search() got an unexpected keyword argument 'num_results'`. However, when I switched to using the **googlesearch-python** package instead of the **google** package, it worked correctly.

**Comment by IbrahimSMo** [comment]
for package google: search() function  takes argument called 'num' not 'num_results'  so i updated it in the code with line 68 and it worked corrected
